#!/usr/bin/env python3
"""Build a Windows folder you can play without installing Python.

This does not replace the script workflow. After a successful build you can still:

  python run_all.py
  python pyBomberMarv.py

The packaged game is written to dist/BomberMarv/BomberMarv.exe.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.join(ROOT, "web_client")
DIST_DIR = os.path.join(ROOT, "dist", "BomberMarv")
DIST_EXE = os.path.join(DIST_DIR, "BomberMarv.exe")
DIST_ZIP = os.path.join(ROOT, "dist", "BomberMarv-windows.zip")


def _resolve_bun() -> str | None:
    bun = shutil.which("bun")
    if bun:
        return bun
    user_profile = os.environ.get("USERPROFILE") or os.environ.get("HOME") or ""
    candidate = os.path.join(user_profile, ".bun", "bin", "bun.exe" if os.name == "nt" else "bun")
    return candidate if os.path.exists(candidate) else None


def _run(command: list[str], cwd: str) -> None:
    print(" ".join(command), flush=True)
    subprocess.run(command, cwd=cwd, check=True)


def _ensure_pyinstaller() -> None:
    try:
        import PyInstaller  # noqa: F401
    except Exception:
        print("Installing PyInstaller...", flush=True)
        _run([sys.executable, "-m", "pip", "install", "pyinstaller"], ROOT)


def _write_icon() -> None:
    src = os.path.join(ROOT, "img", "logo.png")
    dest_dir = os.path.join(ROOT, "build")
    dest = os.path.join(dest_dir, "bombermarv.ico")
    if not os.path.isfile(src):
        return
    os.makedirs(dest_dir, exist_ok=True)
    try:
        from PIL import Image

        image = Image.open(src).convert("RGBA")
        image.save(dest, sizes=[(256, 256), (128, 128), (64, 64), (32, 32), (16, 16)])
        print(f"Wrote {dest}", flush=True)
    except Exception as exc:
        print(f"Skipping exe icon ({exc})", flush=True)


def _write_spec(icon_path: str | None) -> str:
    """Write a PyInstaller spec under build/ so the gitignored *.spec pattern is fine."""
    spec_dir = os.path.join(ROOT, "build")
    os.makedirs(spec_dir, exist_ok=True)
    spec_path = os.path.join(spec_dir, "BomberMarv.spec")
    icon_line = f"    icon=r'{icon_path}',\n" if icon_path and os.path.isfile(icon_path) else ""
    spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Generated by compile_windows.py — do not commit.

block_cipher = None

a = Analysis(
    [r'{os.path.join(ROOT, "pyBomberMarv.py")}'],
    pathex=[r'{ROOT}'],
    binaries=[],
    datas=[
        (r'{os.path.join(ROOT, "img")}', 'img'),
        (r'{os.path.join(ROOT, "sounds")}', 'sounds'),
        (r'{os.path.join(ROOT, "web_client", "dist")}', 'web_client_dist'),
    ],
    hiddenimports=[
        'pygame',
        'pygame.gfxdraw',
        'numpy',
        'psutil',
        'websockets',
        'aiohttp',
        'aiohttp.web',
        'msgpack',
        'PIL',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BomberMarv',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
{icon_line})
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='BomberMarv',
)
"""
    with open(spec_path, "w", encoding="utf-8") as handle:
        handle.write(spec)
    print(f"Wrote {spec_path}", flush=True)
    return spec_path


def _zip_dist() -> None:
    if os.path.isfile(DIST_ZIP):
        os.remove(DIST_ZIP)
    shutil.make_archive(DIST_ZIP[:-4], "zip", os.path.dirname(DIST_DIR), os.path.basename(DIST_DIR))
    print(f"Zipped package: {DIST_ZIP}", flush=True)


def _build_web_client() -> None:
    bun = _resolve_bun()
    if bun:
        _run([bun, "install", "--frozen-lockfile"], WEB)
        _run([bun, "run", "build"], WEB)
    else:
        npm = shutil.which("npm")
        if not npm:
            raise RuntimeError("Need bun or npm to build the web client before packaging")
        _run([npm, "install"], WEB)
        _run([npm, "run", "build"], WEB)
    index = os.path.join(WEB, "dist", "index.html")
    if not os.path.isfile(index):
        raise RuntimeError(f"Web client build did not produce {index}")


def main() -> int:
    if os.name != "nt":
        print("compile_windows.py is meant to run on Windows.", flush=True)
        return 1
    print("Building BomberMarv Windows package...", flush=True)
    print("Python script play is unchanged: python run_all.py / python pyBomberMarv.py", flush=True)
    _build_web_client()
    _ensure_pyinstaller()
    _write_icon()
    icon_path = os.path.join(ROOT, "build", "bombermarv.ico")
    spec_path = _write_spec(icon_path if os.path.isfile(icon_path) else None)
    _run(
        [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--clean",
            spec_path,
        ],
        ROOT,
    )
    if not os.path.isfile(DIST_EXE):
        print("Build finished but BomberMarv.exe was not found.", flush=True)
        return 1
    _zip_dist()
    print(flush=True)
    print(f"Windows build ready: {DIST_EXE}", flush=True)
    print(f"Zip for GitHub Releases: {DIST_ZIP}", flush=True)
    print("Copy the whole dist/BomberMarv folder. Double-click BomberMarv.exe to host.", flush=True)
    print("LAN clients open http://<this-pc>:8080  (also printed in the exe console)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
