# --- Logging Setup ---
def setup_logging(logfile):
    import logging
    import sys
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(threadName)s %(message)s",
        handlers=[
            logging.FileHandler(logfile, mode='a', encoding='utf-8'),
            logging.StreamHandler(sys.__stdout__)
        ]
    )
    class StreamToLogger:
        def __init__(self, level):
            self.level = level
        def write(self, message):
            if message.strip():
                logging.log(self.level, message.strip())
        def flush(self): pass
    sys.stdout = StreamToLogger(logging.INFO)
    sys.stderr = StreamToLogger(logging.ERROR)
    import builtins
    builtins.print = lambda *args, **kwargs: logging.info(' '.join(str(a) for a in args))
# --- End Logging Setup ---

import asyncio
import websockets
import aiohttp
from aiohttp import web
import threading
import json
import queue
import profiler
import os
import uuid

# Path to the JPEG file generated by the game
FRAME_PATH = "current_frame.jpg"

# Set the frame rate (frames per second)
FRAME_RATE = 30

# Set the port for the WebSocket server
PORT = 8765

HTTP_PORT = 8080
CLIENT_HTML = "client.html"

WS_SERVER_VERSION = "1.2.0"
HTTP_SERVER_VERSION = "1.1.0"

# Only call setup_logging at the top-level, not inside run_server_with_queue (to avoid double setup)
setup_logging("ws_server.log")

def run_server_with_queue(frame_queue, input_queue, log_path=None):
    import asyncio
    import websockets
    import threading
    import aiohttp
    from aiohttp import web
    import json
    import profiler
    import uuid

    FRAME_RATE = 30
    PORT = 8765
    HTTP_PORT = 8080
    CLIENT_HTML = "client.html"

    latest_frame = None
    latest_frame_lock = threading.Lock()
    client_id_counter = 0
    client_id_lock = threading.Lock()
    client_ids = set()

    def frame_updater():
        nonlocal latest_frame
        while True:
            try:
                frame = frame_queue.get(timeout=1)
                with latest_frame_lock:
                    latest_frame = frame
            except Exception:
                continue

    threading.Thread(target=frame_updater, daemon=True).start()

    async def stream_frames(websocket):
        nonlocal client_id_counter
        # Assign a unique player_id to this client
        with client_id_lock:
            player_id = client_id_counter
            client_id_counter += 1
            client_ids.add(player_id)
        # Send player_id to client as a JSON message
        await websocket.send(json.dumps({"type": "player_id", "player_id": player_id}))
        print(f"Client connected: {websocket.remote_address}, assigned player_id: {player_id}")
        pressed_keys = set()
        last_sent_frame = None
        try:
            while True:
                try:
                    msg = await asyncio.wait_for(websocket.recv(), timeout=0.025)
                    if msg:
                        try:
                            data = json.loads(msg)
                            data['player_id'] = player_id  # Attach player_id to all key events
                            if data.get('type') == 'keydown':
                                pressed_keys.add(data.get('key'))
                            elif data.get('type') == 'keyup':
                                pressed_keys.discard(data.get('key'))
                            print(f"Player {player_id} pressed keys: {sorted(pressed_keys)}")
                            input_queue.put(data)
                        except Exception as e:
                            print(f"Error parsing input: {e}")
                except asyncio.TimeoutError:
                    pass
                with latest_frame_lock:
                    frame = latest_frame
                if frame is not None and frame is not last_sent_frame:
                    try:
                        await websocket.send(frame)
                        last_sent_frame = frame
                    except Exception as e:
                        print(f"Error sending frame: {e}")
                        break
                else:
                    await asyncio.sleep(0.001)
        except websockets.ConnectionClosed as cc:
            print(f"WebSocket connection closed: {cc}")
        except Exception as e:
            print(f"Error in stream_frames: {e}")
        print(f"Exiting stream_frames for {websocket.remote_address}, player_id: {player_id}")
        with client_id_lock:
            client_ids.discard(player_id)

    async def handle_root(request):
        return web.FileResponse(CLIENT_HTML)

    async def handle_static(request):
        path = request.match_info.get('filename', None)
        if path and os.path.exists(path):
            return web.FileResponse(path)
        return web.Response(status=404)

    async def handle_versions(request):
        return web.json_response({
            "ws_server": WS_SERVER_VERSION,
            "http_server": HTTP_SERVER_VERSION
        })

    def start_http_server():
        app = web.Application()
        app.router.add_get('/', handle_root)
        app.router.add_get('/{filename}', handle_static)
        app.router.add_get('/versions', handle_versions)
        runner = web.AppRunner(app)
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        async def run():
            await runner.setup()
            site = web.TCPSite(runner, '0.0.0.0', HTTP_PORT)
            await site.start()
            print(f"HTTP server started on port {HTTP_PORT}")
            while True:
                await asyncio.sleep(3600)
        loop.run_until_complete(run())

    async def main():
        print(f"Starting WebSocket server on port {PORT}")
        ws_server = websockets.serve(stream_frames, "0.0.0.0", PORT, max_size=2**22)
        threading.Thread(target=start_http_server, daemon=True).start()
        await ws_server
        await asyncio.Future()  # run forever

    asyncio.run(main())
