import logging
import sys
import os

def setup_logging(logfile):
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(threadName)s %(message)s",
        handlers=[
            logging.FileHandler(logfile, mode='a', encoding='utf-8'),
            logging.StreamHandler(sys.__stdout__)
        ]
    )
    class StreamToLogger:
        def __init__(self, level):
            self.level = level
        def write(self, message):
            if message.strip():
                logging.log(self.level, message.strip())
        def flush(self): pass
    sys.stdout = StreamToLogger(logging.INFO)
    sys.stderr = StreamToLogger(logging.ERROR)
    import builtins
    builtins.print = lambda *args, **kwargs: logging.info(' '.join(str(a) for a in args))

# Ensure logging is set up at the very top, before any print/logging can occur
setup_logging("ws_server.log")

import asyncio
import websockets
import aiohttp
from aiohttp import web
import threading
import json
import queue
import profiler

# Path to the JPEG file generated by the game
FRAME_PATH = "current_frame.jpg"

# Set the frame rate (frames per second)
FRAME_RATE = 30

# Set the port for the WebSocket server
PORT = 8765

HTTP_PORT = 8080
CLIENT_HTML = "client.html"

WS_SERVER_VERSION = "1.2.0"
HTTP_SERVER_VERSION = "1.1.0"

async def stream_frames(websocket):
    print(f"Client connected: {websocket.remote_address}")
    last_sent = None
    pressed_keys = set()
    try:
        while True:
            print("Top of server loop, waiting for client message...")
            try:
                print("Waiting for client message...")
                try:
                    msg = await asyncio.wait_for(websocket.recv(), timeout=0.1)
                    print("Message received!")
                    if msg:
                        print("Raw message:", msg)
                        try:
                            data = json.loads(msg)
                            print(f"Received input: {data}")
                            # Track pressed keys
                            if data.get('type') == 'keydown':
                                pressed_keys.add(data.get('key'))
                            elif data.get('type') == 'keyup':
                                pressed_keys.discard(data.get('key'))
                            print(f"Currently pressed keys from client: {sorted(pressed_keys)}")
                        except Exception as e:
                            print(f"Error parsing input: {e}")
                except asyncio.TimeoutError:
                    pass
                # Read the latest frame only if file size is nonzero
                if os.path.exists(FRAME_PATH) and os.path.getsize(FRAME_PATH) > 0:
                    with open(FRAME_PATH, "rb") as f:
                        frame = f.read()
                    # Only send if the frame has changed
                    if frame != last_sent:
                        await websocket.send(frame)
                        last_sent = frame
                else:
                    print(f"Frame file {FRAME_PATH} does not exist or is empty.")
                await asyncio.sleep(1 / FRAME_RATE)
            except websockets.ConnectionClosed as cc:
                print(f"WebSocket connection closed: {cc}")
                break
            except Exception as e:
                print(f"Error in stream_frames inner loop: {e}")
                await asyncio.sleep(1)
    except Exception as e:
        print(f"Error in stream_frames outer: {e}")
    print(f"Exiting stream_frames for {websocket.remote_address}")

async def handle_root(request):
    return web.FileResponse(CLIENT_HTML)

async def handle_static(request):
    path = request.match_info.get('filename', None)
    if path and os.path.exists(path):
        return web.FileResponse(path)
    return web.Response(status=404)

async def handle_versions(request):
    # Read game version from pyBomberMarv.py
    game_version = "unknown"
    try:
        with open("pyBomberMarv.py", "r", encoding="utf-8") as f:
            for line in f:
                if line.strip().startswith("GAME_VERSION"):
                    game_version = line.split("=")[1].strip().replace('"', '').replace("'", "")
                    break
    except Exception as e:
        game_version = f"error: {e}"
    return web.json_response({
        "ws_server": WS_SERVER_VERSION,
        "http_server": HTTP_SERVER_VERSION
    })

def start_http_server():
    app = web.Application()
    app.router.add_get('/', handle_root)
    app.router.add_get('/{filename}', handle_static)
    app.router.add_get('/versions', handle_versions)
    runner = web.AppRunner(app)
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    async def run():
        await runner.setup()
        site = web.TCPSite(runner, '0.0.0.0', HTTP_PORT)
        await site.start()
        print(f"HTTP server started on port {HTTP_PORT}")
        while True:
            await asyncio.sleep(3600)
    loop.run_until_complete(run())

async def main():
    
    import profiler
    
    profiler.profile_start()
    print(f"Starting WebSocket server on port {PORT}")
    ws_server = websockets.serve(stream_frames, "0.0.0.0", PORT, max_size=2**22)
    # Start HTTP server in a thread
    threading.Thread(target=start_http_server, daemon=True).start()
    await ws_server
    await asyncio.Future()  # run forever
    profiler.profile_end()

def run_server_with_queue(frame_queue, log_path=None):
    if log_path:
        setup_logging(log_path)
    import asyncio
    import websockets
    import threading
    import aiohttp
    from aiohttp import web
    import json

    FRAME_RATE = 30
    PORT = 8765
    HTTP_PORT = 8080
    CLIENT_HTML = "client.html"

    async def stream_frames(websocket):
        print(f"Client connected: {websocket.remote_address}")
        last_sent = None
        pressed_keys = set()
        try:
            while True:
                try:
                    try:
                        msg = await asyncio.wait_for(websocket.recv(), timeout=0.1)
                        if msg:
                            try:
                                data = json.loads(msg)
                                if data.get('type') == 'keydown':
                                    pressed_keys.add(data.get('key'))
                                elif data.get('type') == 'keyup':
                                    pressed_keys.discard(data.get('key'))
                                print(f"Currently pressed keys from client: {sorted(pressed_keys)}")
                            except Exception as e:
                                print(f"Error parsing input: {e}")
                    except asyncio.TimeoutError:
                        pass
                    # Get the latest frame from the queue
                    try:
                        frame = frame_queue.get(timeout=0.1)
                        if frame != last_sent:
                            await websocket.send(frame)
                            last_sent = frame
                    except queue.Empty:
                        pass
                    await asyncio.sleep(1 / FRAME_RATE)
                except websockets.ConnectionClosed as cc:
                    print(f"WebSocket connection closed: {cc}")
                    break
                except Exception as e:
                    print(f"Error in stream_frames inner loop: {e}")
                    await asyncio.sleep(1)
        except Exception as e:
            print(f"Error in stream_frames outer: {e}")
        print(f"Exiting stream_frames for {websocket.remote_address}")

    async def handle_root(request):
        return web.FileResponse(CLIENT_HTML)

    async def handle_static(request):
        path = request.match_info.get('filename', None)
        if path and os.path.exists(path):
            return web.FileResponse(path)
        return web.Response(status=404)

    async def handle_versions(request):
        return web.json_response({
            "ws_server": WS_SERVER_VERSION,
            "http_server": HTTP_SERVER_VERSION
        })

    def start_http_server():
        app = web.Application()
        app.router.add_get('/', handle_root)
        app.router.add_get('/{filename}', handle_static)
        app.router.add_get('/versions', handle_versions)
        runner = web.AppRunner(app)
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        async def run():
            await runner.setup()
            site = web.TCPSite(runner, '0.0.0.0', HTTP_PORT)
            await site.start()
            print(f"HTTP server started on port {HTTP_PORT}")
            while True:
                await asyncio.sleep(3600)
        loop.run_until_complete(run())

    async def main():
        print(f"Starting WebSocket server on port {PORT}")
        ws_server = websockets.serve(stream_frames, "0.0.0.0", PORT, max_size=2**22)
        threading.Thread(target=start_http_server, daemon=True).start()
        await ws_server
        await asyncio.Future()  # run forever

    asyncio.run(main())

if __name__ == "__main__":
    asyncio.run(main())
